spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:37327/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
